// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDR3fW3YTTY3-zPi9_Nj4TnL_fmH4nT4U',
    appId: '1:57788957382:web:12d1c17a38617882574dc7',
    messagingSenderId: '57788957382',
    projectId: 'mindheal-38fcc',
    authDomain: 'mindheal-38fcc.firebaseapp.com',
    storageBucket: 'mindheal-38fcc.firebasestorage.app',
    measurementId: 'G-KXXE6KM8BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozUwU-cVNk16PnM5d7aZFyod5iCTw8Ag',
    appId: '1:57788957382:android:bbca81b6c0e3ad1d574dc7',
    messagingSenderId: '57788957382',
    projectId: 'mindheal-38fcc',
    storageBucket: 'mindheal-38fcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-pxFw5-O8HkTZvZLG0kHa_OMiTmtHXds',
    appId: '1:57788957382:ios:75e0ddd4cfa871ec574dc7',
    messagingSenderId: '57788957382',
    projectId: 'mindheal-38fcc',
    storageBucket: 'mindheal-38fcc.firebasestorage.app',
    iosBundleId: 'com.example.mindheal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-pxFw5-O8HkTZvZLG0kHa_OMiTmtHXds',
    appId: '1:57788957382:ios:75e0ddd4cfa871ec574dc7',
    messagingSenderId: '57788957382',
    projectId: 'mindheal-38fcc',
    storageBucket: 'mindheal-38fcc.firebasestorage.app',
    iosBundleId: 'com.example.mindheal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDR3fW3YTTY3-zPi9_Nj4TnL_fmH4nT4U',
    appId: '1:57788957382:web:d6a1cdf47e4decb8574dc7',
    messagingSenderId: '57788957382',
    projectId: 'mindheal-38fcc',
    authDomain: 'mindheal-38fcc.firebaseapp.com',
    storageBucket: 'mindheal-38fcc.firebasestorage.app',
    measurementId: 'G-5LPTCT7QMZ',
  );

}